name: Android Instrumented Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Java
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 4️⃣ Build aplikasi
      - name: Build debug APK
        run: ./gradlew assembleDebug

      # 5️⃣ Jalankan tes dengan emulator headless
      - name: Run instrumented tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio

      # 6️⃣ Upload laporan hasil tes (opsional)
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-reports
          path: app/build/reports/androidTests/connected/
