name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3️⃣ Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 4️⃣ Set permission untuk gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5️⃣ Build project
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 6️⃣ Jalankan instrumented test di emulator
      - name: Run instrumented tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: ./gradlew connectedDebugAndroidTest

      # 7️⃣ Upload laporan hasil test (opsional tapi sangat disarankan)
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-reports
          path: app/build/reports/androidTests/connected/
